var age = 25;
age = true;
console.log(age);
age = "hello";
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push("mario");
console.log(mixed);
var ninja;
ninja = { name: "yoshi", age: 26 };
console.log(ninja);
ninja = { name: 25, age: "26" };
console.log(ninja);
